--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.53.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21.12.2017 г. 22:41:34
-- Server version: 5.7.17-log
-- Client version: 4.1
--


--
-- Definition for database garage
--
DROP DATABASE IF EXISTS garage;
CREATE DATABASE IF NOT EXISTS garage
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE garage;

--
-- Definition for table t_parking_level
--
CREATE TABLE IF NOT EXISTS t_parking_level (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TIME_START DATETIME DEFAULT NULL,
  TIME_EXIT DATETIME DEFAULT NULL,
  CAPACITY INT(11) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PARKING_LOT_ID INT(11) DEFAULT NULL,
  VEHICLE_ID INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX FKb9mjw14i4tyf3jq36vjgxam7n (PARKING_LOT_ID),
  INDEX FKhiuf4g1hv2jix220b36vs3n3e (VEHICLE_ID),
  UNIQUE INDEX UK_2ap0mrippmye9x4fcu5x901yj (NAME),
  UNIQUE INDEX UK_8h9kme24f6no04jxnq2sb29rf (CAPACITY)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_parking_lot
--
CREATE TABLE IF NOT EXISTS t_parking_lot (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  IS_FREE TINYINT(1) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PARKING_LEVEL_ID INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX FKmjt5hep9tq579lqx4673iomdw (PARKING_LEVEL_ID),
  UNIQUE INDEX UK_a7jwm5iul0js1kosunoqnwhc6 (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_vehicle
--
CREATE TABLE IF NOT EXISTS t_vehicle (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  PLATE_NUMBER VARCHAR(255) NOT NULL,
  VEHICLE_TYPE_ID INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX FKcieg3ukfgxpd807ii1nw0lt49 (VEHICLE_TYPE_ID),
  UNIQUE INDEX UK_ov10hyplvkpr9jj2o0fjdjbcg (PLATE_NUMBER)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table t_vehicle_type
--
CREATE TABLE IF NOT EXISTS t_vehicle_type (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UK_8l18wy237yghuohoie2a765o (NAME)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table t_parking_level
--

-- Table garage.t_parking_level does not contain any data (it is empty)

-- 
-- Dumping data for table t_parking_lot
--

-- Table garage.t_parking_lot does not contain any data (it is empty)

-- 
-- Dumping data for table t_vehicle
--

-- Table garage.t_vehicle does not contain any data (it is empty)

-- 
-- Dumping data for table t_vehicle_type
--

-- Table garage.t_vehicle_type does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;